name: 🐍 Generate GitHub Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Generate GitHub Snake SVG & GIF Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-ocean.svg?color_snake=#ff6f00&color_dots=#ffee58,#ffca28,#ffa000,#ff8f00,#ff6f00
            dist/github-snake-neon.svg?color_snake=#39ff14&color_dots=#39ff14,#00e0ff,#ff00ff,#ff0090,#ff9900
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
